[tox]
skipsdist = True
envlist = test
all_sources = src/ tests/
requires =
    tox >= 4.4.6
    tox-docker >= 4.0
    tox-uv
provision_tox_env=provision

[testenv]
runner = uv-venv-lock-runner
description = Run tests with docker container controlled by tox

setenv =

passenv =

allowlist_externals =
    uv
    python
    true

commands_pre = uv sync

[testenv:test]
commands =
    uv run ruff format --diff {posargs:.}
    uv run ruff check --no-fix --statistics --output-format concise {posargs:.}
    uv run mypy --cache-dir /dev/null {posargs:src}
    uv run pytest {posargs:tests}

[testenv:debug]
runner = uv-venv-lock-runner
description = Run pytest with args (default '--lf --pdb')
commands =
    pytest {posargs:--lf --pdb}
